### ISSUE TITLE
remove warning for time limited item

### ISSUE THREAD

**Issue by itosmoti** [ebisuke/TosAddons#195]
Ep12で実装される追加倉庫が利用できる環境下だと、追加倉庫に一切アイテムが保管できなくなる現象が発生します
iTosで当アドオンのON・OFFと環境の異なるPC2台で確認しました
(Ep11までは問題なく利用できていました)

例えば元々のチーム倉庫で51スロット利用可能な場合、追加倉庫1～4のタブ自体は利用できるのですが、元々のチーム倉庫スロットと追加倉庫1～4に保管しているアイテムのスロット数が51を超えると保管が出来なくなります

**Comment by ebisuke** [comment]
ご報告ありがとうございます。
現時点でJTOSにEP12が来ておりませんためバージョン混在による問題が発生する可能性・実装の煩雑さを鑑み、対応を控えております。
JTOSがアップデートされ次第対応する予定です。よろしくお願いいたします。

**Comment by itosmoti** [comment]
ご返信ありがとうございます

後からの補足となり恐縮ですが、現時点での修正ではなく、高確率でJTOSでも同症状が発生すると考えたためご連絡した次第です

ebisukeさんのアドオンはその他含め、非常にお世話になっており、助かっています
もしJTOSでも確認された場合はいずれご対応いただけると助かります
