### ISSUE TITLE
ItemBuffMachine Possible Solution

### ISSUE THREAD

**Issue by Vanguardsify** [ebisuke/TosAddons#218]
Hello,
It's me again with some random and crazy idea's...this time the idea is a possible solution for ItemBuffMachine. Since you said on discord "ItemBuffMachine used to apply Squire's item buffs without removing the equipment, but a recent patch prevented that method from working.
I need to rethink how to implement it."

well i think i know how to imprement a new method...i dont know if possible...since i dont know what is making impossible to use the addon...

The idea is one function that already exist in AWW(one of yours addons) together with ItemBuffMachine. Well lets go for the idea:

 - 1 Button for Config wich would be one thing like that [https://forum.treeofsavior.com/uploads/default/original/3X/0/f/0f073350a68f893968a545a59c1718268c00ecbf.png](url) But, wont be required the register of acessories, since they cant be buffed, so we put the items there and save the loadout
 - 1 Button to Buff: here is what basically ItemBuffMachine already does, but with a small difference; The difference is that when we click "Buff" the addon will Unequip our gear and start buffing one by one like was before. When it finish Buffing our items it Equip our gear again and done.
 
Basically the idea is that...but since we saving loadout's...we could have the idea i gave on the other issue i opened with only a "weapon" buffs and "full gear" buff Buttons, since we should save our loadout to buff...so with loadout's system we could make that and just select wich loadout ItemBuffMachine will apply the buff...simillar to what Aww does, where we could make multiple loadouts and select one and deposit/withdraw.

Well, i can see also a bad side on this, since ItemBuffMachine simple buff all items without the wait of the time the addon will spend to unequip our gear > buff > then again another seconds to fully equip our gear again.

That is all for squire version.

Also i read that IBM was able to buff on Enchanter(Enchanter Class), the idea would be almost the same...but here we would have to put only 2 pieces of our gear(Armor and Pants) and we could have a way to pre-select wich enchant we would like to use on the item, after that we save it as a loadout similar to Aww, then open Character store and select our options and "Buff" ; after that the addon would unequip our gear, put it on character store and auto select the "enchant" we pre-selected before and apply it.

On a enchant pre-select could be 1 enchant per Piece or 1 enchant for both pieces like: https://pasteboard.co/Jsey4rP.png or https://pasteboard.co/JseykSk.png... Well those images are just to illustrate.... Also tell me if u cant see them.

Tell me, what u think about it...if possible or not, how hard it would be... also if u dont understand some part here...tell me so i can try to re-explain what is in my mind, because sometimes i dont know the best way to communicate in english since not my main tongue(also not yours since all descriptions of your addons are in Japanese if i and google are not wrong).

Thanks for your time. ^^

**Comment by ebisuke** [comment]
I released v0.0.6. Maybe fixed this issue.
