### ISSUE TITLE
Doubt about aww

### ISSUE THREAD

**Issue by Vanguardsify** [ebisuke/TosAddons#219]
Hi,

I was trying to deposit my set into Storage with Aww and it throw me an "[AWW]Insufficient empty slots", so i was wondering how many slots free should i have so it dont say that ? i was trying to put only my set (Armor, Pants, Gloves, Boots) wich counts total of 4 items... and in my Storage had 14 Slots Free (Last slot doesnt count, so total 13)...i was wondering, how many free slots i need then?

Aww Config can be put 16 items, so it's so i need 17 Slots (16 + 1) ?

Sorry for bothering u too much... i mean, i'm opening "issue" alot of times i think.
Also thx for ur addons, i appreciat alot those QoL(Quality of Life) Addons.
Have a nice day/night.

**Comment by ebisuke** [comment]
Thanks for use.
There is a bug in the ToS that prevents you from bringing in stackable items when all the slots in the warehouse are used. 
To avoid this, the last slot in each warehouse is not used.

**Comment by Vanguardsify** [comment]
Yes, but what about "[AWW]Insufficient empty slots" ?

I mean... When i was trying to deposit 4 Items ( Armor, Pants, Gloves, Boots ) it throw me that error...while in reallity i had more than 5 slots free (14 Slots in total but since we do not count last one, we have a total of 13 then)... So, how many slots in reallity i should have ?  It's the ammount of items i can put on Aww Config even not using them(16+1) ?

**Comment by ebisuke** [comment]
OK...maybe it's possible that the confirmation of the available slots may not be accurate, I'll check later.

**Comment by ebisuke** [comment]
Hmmm, you're right, it looks like I need a 16+1 slot at the moment. I was mistaken.
I'll leave this one as an issue until it's corrected.

**Comment by Vanguardsify** [comment]
Ok...so was a "bug"
Hope i'm not bothering u with that amount of "issues" i'm opening

Have a nice day/night.
Also thanks again for your attention and yours addons

**Comment by Vanguardsify** [comment]
Eerm, Hello, xD

I'm here to try to update u about the aww "problem"... i tried some amount of slots on accounts and this is what i have:

[https://www.youtube.com/watch?v=LBIdcCcvE5g](url) in this first video it worked Fine, Aww managed to Unequip my 4 armor parts and deposit it without any error... did it multiple times, no error, working perfectly fine. Note: Here i was using Varna to test and i had an total of 5 Slots Free.

[https://www.youtube.com/watch?v=FRDpaeAXCes&ab_channel=Vanguardsz](url) Here i tested again, with another set, also with 4 armor parts...also worked perfectly fine. Note: Here i had 4 Slots free for 4 Pieces of set, so Aww deposited last part of my set on another Tab, no problem at all, also worked really good (I Didnt know Aww could do that automatically, i think it was going to throw an error on me.). Its Really nice to know it can deposit like at any Tab and Withdraw from any of them too with a simple click.

[https://www.youtube.com/watch?v=8mVOKWAYrZ4&ab_channel=Vanguardsz](url) Well here is the problem....for some reasson i have 20 Free slots and i cant deposit... also was 4 armor parts like all other 2 videos...but for some reasson it Say "Insufficient empty slots" wich makes no sense.... well maybe because this accounts does not have a token on it ? it's the only thing different i can think about when comparing those accounts beside the sets/ichors on it... Note: It was working fine when i had a token on it, so this is why i think there is a relation with not having a active token.

Well just did this because i wanted to update u about the bug with a better Explanation, also with a video where u can better see what is happening and have a better conclusion....

Even u was thinking that u need 16+1 slot's...maybe u hadn't token too ? or u was analysing the code ? idk... '-'.

Well Again, Sorry for bothering and Thx for yours addons.

**Comment by Vanguardsify** [comment]
Forgot to close
Also idk if problem was fixed, since it's a problem that happened when i was without token...anyway i dont stay without token anymore...
Thx anyway.

**Comment by ebisuke** [comment]
I apologize for the delay in responding.
I'm not sure if it's fixed now, so I'll leave this Issue as is.

**Comment by Vanguardsify** [comment]
well, i can test it...just let my token expire ^^

Also, the bug is not a great problem...the problem is that normally i wasnt using token if i hadn't nothing to sell....but now drops are affected by token, so there is no reason to do things without token if u wont have chance to earn more items.

Also...no need to apologize, all yours addons are fantastic... it's just a minor bug

**Comment by Vanguardsify** [comment]
Small Update on Aww,
those days i recorded small vid about the problem again, but now i found more things about how to probably trigger it.

Somehow i think AWW is trying to "Stack" the Equipments for some reason.
in the vids below, i used two dif Accounts to record about this thing i found. Where both had no Token at the moment i recorded about it.

Problem:  https://youtu.be/6333vcD7fIs
Normal: https://youtu.be/dErlQBvN_Dc (i Forgot to show the Storage here, but there is nothing on other tabs)

The version in Use is 0.4.4 ... but i saw on Git that u Uploaded new Version today with card's implementation

Also as i said before u reopening the issue, this is no problem for me anymore, but since u keep it open, i think u trying to fix this...so since i'm the one that reported the issue, i'll try to give u as much evidence i have and got to try to help.

Also, thx again for yours addons, they are so much QoL (Quality of Life - Addons that do small things automatically that do no warm for other...)

I'll try to test 0.5 later to see if the problem happens or not in this new version.

**Comment by ebisuke** [comment]
Thank you.
I think this is a rare occurrence, so it's not a priority for us to fix, but I'd like to keep it open because it's a bug and we want to remember it.
I'd like to leave it open because it's a bug and I want to remember it so I don't forget it. I'm currently omitting the check for removing equipment and making sure it was removed correctly, so adding that might help, but it's a lot to fix and I think it'll be a long time before it's implemented.

Translated with www.DeepL.com/Translator (free version)

**Comment by ebisuke** [comment]
I've decided to rebuild it after all, so I'm closing this issue. I apologize for the delay in responding to various issues.
